spring:
  kafka:
    template:
      default-topic: notificationTopic
    consumer:
      group-id: notificationId
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      properties:
        spring:
          json:
            type:
              mapping: event:com.maicol1912.microservice.dto.OrderPlacedEvent
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
    bootstrap-servers: localhost:9092
  zipkin:
    base-url: http://localhost:9411
  application:
    name: notification-service
  sleuth:
    sampler:
      probability: '1.0'
eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    serviceUrl:
      defaultZone: http://eureka:password@localhost:8761/eureka
server:
  port: ${PORT:0}
