spring:
  cloud:
    gateway:
      routes[2]:
        uri: lb://inventory-service
        id: inventory-service
        predicates[0]: Path=/api/inventory
      routes[0]:
        id: product-service
        uri: lb://product-service
        predicates[0]: Path=/api/product
      routes[3]:
        id: discovery-server
        predicates[0]: Path=/eureka/web
        filters[0]: SetPath=/
        uri: http://localhost:8761
      routes[1]:
        id: order-service
        predicates[0]: Path=/api/order
        uri: lb://order-service
      routes[4]:
        uri: http://localhost:8761
        id: discovery-server-static
        predicates[0]: Path=/eureka/**
  application:
    name: api-gateway
  sleuth:
    sampler:
      probability: '1.0'
  zipkin:
    base-url: http://localhost:9411
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8181/realms/spring-boot-microservices-realm
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:password@localhost:8761/eureka
