eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    serviceUrl:
      defaultZone: http://eureka:password@localhost:8761/eureka
spring:
  zipkin:
    base-url: http://localhost:9411
  application:
    name: product-service
  sleuth:
    sampler:
      probability: '1.0'
  data:
    mongodb:
      uri: mongodb://localhost:27017/product-service
server:
  port: ${PORT:0}
