spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    url: jdbc:mysql://localhost:3306/inventory-service
    password: '1234'
  zipkin:
    base-url: http://localhost:9411
  application:
    name: inventory-service
  sleuth:
    sampler:
      probability: '1.0'
  jpa:
    hibernate:
      ddl-auto: create-drop
eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    serviceUrl:
      defaultZone: http://eureka:password@localhost:8761/eureka
server:
  port: ${PORT:0}
